title="ATKIS VKG"

[[tabGroups]]
name="Settlement"

[[tabGroups.tabs]]
name="SIE01: site, named location"
query = """
# SIE01: Find locations likely to be close to Denmark
PREFIX : <http://example.org/ontologies/atkis#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
?x a :Settlement .
OPTIONAL {?x rdfs:label ?name .}
?x :regionalLanguage ?secondName .
# Based on second name usage of Danish alphabet these locations are near the border with Denmark
  FILTER(CONTAINS(?secondName, "å") || CONTAINS(?secondName, "ø"))
  ?x geo:hasGeometry/geo:asWKT ?xGeom .
}
"""

[[tabGroups.tabs]]
name="SIE02: Areas dominated by buildings"
query = """
# SIE02: Find either 1) all golf courts in the dataset
PREFIX : <http://example.org/ontologies/atkis#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
?x a :AreaDominatedByBuilding .
OPTIONAL {?x rdfs:label ?name .}

  # Find golf courts
  ?x :function [rdfs:label ?function] .
  FILTER(LANG(?function) = "de" && STR(?function) = "Golf")
  ?x geo:hasGeometry/geo:asWKT ?xGeom .

}
"""

[[tabGroups.tabs]]
name="SIE03: buildings and other facilities"
query = """
# SIE03: Find all stadiums
PREFIX : <http://example.org/ontologies/atkis#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
?x a :BuildingFacility .
OPTIONAL {?x rdfs:label ?name .}

  # Find all stadiums
  ?x :structureFunction [rdfs:label ?function] .
  FILTER(LANG(?function) = "en" && STR(?function) = "Stadium")
  ?x geo:hasGeometry/geo:asWKT ?xGeom .

}
"""

[[tabGroups.tabs]]
name="SIE04: special facilities at settlement areas"
query = """
# SIE04: Find all river boat lift structures
PREFIX : <http://example.org/ontologies/atkis#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
?x a :SpecialFacility .
OPTIONAL {?x rdfs:label ?name .}

  # Find all river boat lifts
  ?x :designFeature [rdfs:label ?riverStructure] .
  FILTER(LANG(?riverStructure) = "en" && STR(?riverStructure) = "Boat lift")
  ?x geo:hasGeometry/geo:asWKT ?xGeom .
}
"""

[[tabGroups.tabs]]
name="SIE05: buildings"
query = """
# SIE05: Find all youth hostels and label on whether they are out of service
PREFIX : <http://example.org/ontologies/atkis#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
?x a :Building .
OPTIONAL {?x rdfs:label ?name .}

  # Find all youth hostels and label whether they are no longer functional
  ?x :buildingFunction [rdfs:label ?buildingFunction] .
  FILTER(LANG(?buildingFunction) = "en" && STR(?buildingFunction) = "Youth Hostel")
  OPTIONAL { ?x :condition [ rdfs:label ?status] . }
  FILTER(!BOUND(?status) || LANG(?status) = "en")
  ?x geo:hasGeometry/geo:asWKT ?xGeom .

}
ORDER BY DESC(?status)
"""

[[tabGroups]]
name="Traffic"

[[tabGroups.tabs]]
name="VER01: road traffic"
query = """
# VER01: Find international roads with specific characteristics
PREFIX : <http://example.org/ontologies/atkis#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
?x a :RoadTraffic .
OPTIONAL {?x rdfs:label ?name .}

  # Find roads of international importance
  ?x :internationalImportance ?hasInternationalImportance . FILTER(?hasInternationalImportance = true) .
  # Filter their number of lanes to be at least 4
  ?x :numberOfLanes ?totalLanes . FILTER(?totalLanes >= 4)
  # Filter their lane length to be above 10 metres
  ?x :widthOfRoadway ?laneLength . FILTER(?laneLength > 10)

  ?x geo:hasGeometry/geo:asWKT ?xGeom .
}
"""

[[tabGroups.tabs]]
name="VER02: paths"
query = """
# VER02: Find main agricultural/farm roads
PREFIX : <http://example.org/ontologies/atkis#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
?x a :Path .
OPTIONAL {?x rdfs:label ?name .}

  # Find main agricultural/farm road
  ?x :function [ rdfs:label ?function] .
  FILTER(LANG(?function) = "de" && STR(?function) = "Hauptwirtschaftsweg")

  ?x geo:hasGeometry/geo:asWKT ?xGeom .
}
"""

[[tabGroups.tabs]]
name="VER03: railway traffic"
query = """
# VER03: Find standard gauge electrified railways
PREFIX : <http://example.org/ontologies/atkis#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
  ?x a :RailwayTraffic .
  OPTIONAL {?x rdfs:label ?name .}

  # Find standard gauge and electrified railways
  ?x :trackGauge [ rdfs:label ?function] .
  FILTER(LANG(?function) = "en" && STR(?function) = "Standard gauge")
  ?x :electrifiedRail ?electrified .
  FILTER(?electrified = TRUE) .

  ?x geo:hasGeometry/geo:asWKT ?xGeom .
}
"""

[[tabGroups.tabs]]
name="VER04: air traffic"
query = """
# VER04: Find airports/heliports with mixed use
PREFIX : <http://example.org/ontologies/atkis#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
  ?x a :AirTraffic .
  OPTIONAL {?x rdfs:label ?name .}

  # Find airports/heliports with mixed civilian and military use
  ?x :usage [ rdfs:label ?usage] .
  FILTER(LANG(?usage) = "en" && STR(?usage) = "Partly civilian, partly military")
  ?x geo:hasGeometry/geo:asWKT ?xGeom .
}
"""

[[tabGroups.tabs]]
name="VER05: shipping traffic"
query = """
# VER05: Find passenger ferry service lines
PREFIX : <http://example.org/ontologies/atkis#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
  ?x a :ShippingTraffic .
  OPTIONAL {?x rdfs:label ?name .}
  # Find routes used for passenger ferry service
  ?x :type [rdfs:label ?shipTrafficType ] .
  FILTER(LANG(?shipTrafficType) = "de" && STR(?shipTrafficType) = "Personenfährverkehr")
  ?x geo:hasGeometry/geo:asWKT ?xGeom .
}
"""

[[tabGroups.tabs]]
name="VER06: transport buildings and facilities"
query = """
# VER06: Find runways
PREFIX : <http://example.org/ontologies/atkis#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
  ?x a :TransportBuildingAndFacility .
  OPTIONAL {?x rdfs:label ?name .}

  # Find runways/landing strips air transport, made of concrete and with width over 50 metres
  ?x :surfaceMaterial [rdfs:label ?surfaceMaterial ] .
  FILTER(LANG(?surfaceMaterial) = "de" && STR(?surfaceMaterial) = "Beton")
  ?x :objectWidth ?width . FILTER(?width > 50)
  ?x :type [rdfs:label ?structureType] .
  FILTER(LANG(?structureType) = "de" && STR(?structureType) = "Startbahn, Landebahn")

  ?x geo:hasGeometry/geo:asWKT ?xGeom .
}
"""

[[tabGroups]]
name="Vegetation"

[[tabGroups.tabs]]
name="VEG01: agricultural area"
query = """
# VEG01: Find fruit and nut plantations
PREFIX : <http://example.org/ontologies/atkis#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
  ?x a :Agricultural .
  OPTIONAL {?x rdfs:label ?name .}

  # Find fruit and nut plantations
  ?x :vegetationFeature [rdfs:label ?agroArea ] .
  FILTER(LANG(?agroArea) = "de" && STR(?agroArea) = "Obst- und Nussplantage")

  ?x geo:hasGeometry/geo:asWKT ?xGeom .
}
"""

[[tabGroups.tabs]]
name="VEG02: forestry use"
query = """
# VEG02: Find forest burial areas
PREFIX : <http://example.org/ontologies/atkis#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
  ?x a :Forestry .
  OPTIONAL {?x rdfs:label ?name .}

  # Find forest burial areas
  ?x :usage [rdfs:label ?usage ] .
  FILTER(LANG(?usage) = "en" && STR(?usage) = "Forest burial area")

  ?x geo:hasGeometry/geo:asWKT ?xGeom .
}
"""

[[tabGroups.tabs]]
name="VEG03: vegetation areas"
query = """
# VEG03: Find vegetation free areas
PREFIX : <http://example.org/ontologies/atkis#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
  ?x a :VegetationArea .
  OPTIONAL {?x rdfs:label ?name .}

  # Find "Vegetation-free area"s
  ?x :function [rdfs:label ?function ] .
  FILTER(LANG(?function) = "de" && STR(?function) = "Vegetationslose Fläche")

  ?x geo:hasGeometry/geo:asWKT ?xGeom .
}
"""

[[tabGroups.tabs]]
name="VEG04: characteristic of vegetation"
query = """
# VEG04: Find areas with trees
PREFIX : <http://example.org/ontologies/atkis#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
  ?x a :VegetationCharacteristic .
  OPTIONAL {?x rdfs:label ?name .}

  # Find areas with trees
  ?x :groundCover [rdfs:label ?groundCover ] .
  FILTER(LANG(?groundCover) = "de" && STR(?groundCover) = "Baumbestand")

  ?x geo:hasGeometry/geo:asWKT ?xGeom .
}
"""

[[tabGroups]]
name="Water bodies"

[[tabGroups.tabs]]
name="GEW01: water bodies"
query = """
# GEW01: Find sea waterways by width
PREFIX : <http://example.org/ontologies/atkis#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
  ?x a :WaterBodyCourse .
  OPTIONAL {?x rdfs:label ?name .}

  # Find sea waterways by width
  ?x :navigationCategory [rdfs:label ?navigationCategory ] .
  FILTER(LANG(?navigationCategory) = "de" && STR(?navigationCategory) = "Seewasserstraße")
  ?x :widthOfWaterbody ?widthOfWaterBody .

  ?x geo:hasGeometry/geo:asWKT ?xGeom .
}
"""

[[tabGroups.tabs]]
name="GEW02: special characteristics of water bodies"
query = """
# GEW02: Find all waterfalls
PREFIX : <http://example.org/ontologies/atkis#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
  ?x a :WaterBodyCharacteristic .
  OPTIONAL {?x rdfs:label ?name .}

  # GEW01: Find all waterfalls
  ?x :type [rdfs:label ?description ] .
  FILTER(LANG(?description) = "de" && STR(?description) = "Wasserfall")

  ?x geo:hasGeometry/geo:asWKT ?xGeom .
}
"""

[[tabGroups.tabs]]
name="GEW03: axis of water line"
query = """
# GEW03: Find all see routes with the waterline axis approximately at the center
PREFIX : <http://example.org/ontologies/atkis#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
  ?x a :WaterLineAxis .
  OPTIONAL {?x rdfs:label ?name .}

  # GEW03: Find all see routes with the waterline axis approximately at the center
  ?x :navigationCategory [rdfs:label ?navigationCategory ] .
  FILTER(LANG(?navigationCategory) = "de" && STR(?navigationCategory) = "Seewasserstraße")
  ?x :waterStationingAxis [rdfs:label ?axisLocation]
  FILTER(LANG(?axisLocation) = "de" && STR(?axisLocation) = "Genäherte Mittellinie in Gewässern")
}
"""

[[tabGroups]]
name="Areas"

[[tabGroups.tabs]]
name="GEB01: administrative areas"
query = """
# GEB01: Find free and Hanseatic area boundaries
PREFIX : <http://example.org/ontologies/atkis#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
  ?x a :Administrative .
  OPTIONAL {?x rdfs:label ?name .}

  # Find free and Hanseatic area boundaries
  ?x :administrativeFunction [rdfs:label ?admBoundary ] .
  FILTER(LANG(?admBoundary) = "de" && STR(?admBoundary) = "Freie und Hansestadt")

  ?x geo:hasGeometry/geo:asWKT ?xGeom .
}
"""

[[tabGroups.tabs]]
name="GEB02: geographical areas"
query = """
# GEB02: Find moorlands
PREFIX : <http://example.org/ontologies/atkis#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
  ?x a :Geographical .
  OPTIONAL {?x rdfs:label ?name .}

  # Find moorlands
  ?x :landscapeType [rdfs:label ?landType ] .
  FILTER(LANG(?landType) = "de" && STR(?landType) = "Moorlandschaft")

  ?x geo:hasGeometry/geo:asWKT ?xGeom .
}
"""

[[tabGroups.tabs]]
name="GEB03: protected areas"
query = """
# GEB03: Find protected nature parks
PREFIX : <http://example.org/ontologies/atkis#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
  ?x a :Protected .
  OPTIONAL {?x rdfs:label ?name .}

  # Find protected nature parks
  ?x :specificationType [rdfs:label ?landType ] .
  FILTER(LANG(?landType) = "de" && STR(?landType) = "Naturpark")

  ?x geo:hasGeometry/geo:asWKT ?xGeom .
}
"""

[[tabGroups]]
name="Relief"

[[tabGroups.tabs]]
name="REL01: relief forms"
query = """
# REL01: Find relief areas with flood protection, storm surge protection and traffic management
PREFIX : <http://example.org/ontologies/atkis#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
  ?x a :Relief .
  OPTIONAL {?x rdfs:label ?name .}

  # Find relief areas with flood protection, storm surge protection and traffic management
  ?x :function [rdfs:label ?description ] .
  FILTER(LANG(?description) = "de" && STR(?description) = "Hochwasserschutz, Sturmflutschutz zugleich Verkehrsführung")

  ?x geo:hasGeometry/geo:asWKT ?xGeom .
}
"""

[[tabGroups.tabs]]
name="REL02: measurement data 3D"
query = """
# REL02: Find measurements above 2500 metres
PREFIX : <http://example.org/ontologies/atkis#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
  ?x a :MeasurementData .
  OPTIONAL {?x rdfs:label ?name .}

  # Find measurements above 2500 metres
  ?x :type [rdfs:label ?description ] .
  ?x :elevation ?elevation .
  FILTER(?elevation > 2500)

  ?x geo:hasGeometry/geo:asWKT ?xGeom .
}
"""

[[tabGroups]]
name="Vertical relation"

[[tabGroups.tabs]]
name="HDU01: relation"
query = """
# HDU01: Vertical relation - Tunnels over which Schwarzwald Railway passes
PREFIX : <http://example.org/ontologies/atkis#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
  ?x a :RailwayTraffic .
  ?x :secondaryLabel ?otherName .
  # Get Black Forest Railway in Baden
  FILTER(?otherName = "Schwarzwaldbahn")
  # Find vertical relation
  ?x :hasDirectlyUnder ?subComponent .
  OPTIONAL { ?subComponent rdfs:label ?railwayComponentName } .
}
"""