version: "3.4"

services:
  db:
    build:
      context: .
      dockerfile: dockerfile
    env_file: .env
    volumes:
      - ./backup:/docker-entrypoint-initdb.d/backup
    ports:
      - "${MAPPED_POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: atkis_db
  ontop:
    image: ontop/ontop:5.0.2
    env_file: .env
    restart: unless-stopped
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/atkis1.ttl
      ONTOP_MAPPING_FILE: /opt/ontop/input/atkis1.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/atkis1.docker.properties
      ONTOP_PORTAL_FILE: /opt/ontop/input/atkis1.portal.toml
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
      ONTOP_DEV_MODE: "true"
    volumes:
      - ./vkg:/opt/ontop/input
      - ./jdbc:/opt/ontop/jdbc
      - ./wait-for-it:/opt/wait-for-it
    entrypoint:
      [
        "/opt/wait-for-it/wait-for-it.sh",
        "db:5432",
        "--timeout=0",
        "--strict",
        "--",
        "/opt/ontop/entrypoint.sh",
      ]
    ports:
      - "${SERVER_PORT}:8080"
